### ISSUE TITLE
Error in Installation of Streamlit components - Stmol and Stspecklit

### ISSUE THREAD

**Issue by avrabyt** [whitphx/stlite#309]
Congratulations on this amazing development @whitphx ! 🎈 

While trying to use these Streamlit components - [Stmol](https://github.com/napoles-uach/stmol) and [Stspeckmol](https://github.com/avrabyt/st-speckmol) , I'm recieving this following errors - 

```
main.23e8ec4a.chunk.js:1 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 553, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'psutil', 'pyzmq>=17', 'pyzmq>=23.0', 'pyzmq>=17', 'argon2-cffi-bindings'
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
```

- The packages are introduced in the `requirements` file which `stilte` inbuilt offers. 
- Tried in Safari and Google Chrome.

As I can understand, the main issue is because the python 3 wheel for the components can't be found. Can you please suggest a workaround for this ? 

Cheers 
Avra

**Comment by whitphx** [comment]
It's due to #5. 
As you thought, it's because there is no installable wheel for the required package.
Unfortunately, there is no workaround for now, from my understanding.
It's Pyodide's limit explained here https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
In this case, `pyzmq` has C-extension that has to be built for Pyodide, in other words, as Wasm-compatible binary.

This can be solved in the future if
* someone, Pyodide's maintainers or some third-party developers build pyzmq (and other necessary C-extension packages) for Pyodide
* OR stlite can find some workaround (maybe at #5)

**Comment by whitphx** [comment]
I found that `stmol==0.0.7` can be installed while `>=0.0.8` does not work which may have introduced some Pyodide-incompatible dependencies.

**Comment by avrabyt** [comment]
Wooh perfect , thanks !! 😊 Let me investigate on the dependencies updated with `>=0.0.8` .

**Comment by whitphx** [comment]
Let me close this issue as it looks stale.
Please reopen it or create a new one if needed.
