### ISSUE TITLE
Embedding  Youtube / Vimeo videos

### ISSUE THREAD

**Issue by ulugeyik** [whitphx/stlite#405]
I am trying to embed Youtube or Vimeo videos and generate a stand-alone application with the  desktop-cli . 

Youtube videos are blocked with the following error:
 electron: Failed to load URL: https://www.youtube.com/embed/myvideo with error: ERR_BLOCKED_BY_CSP

Vimeo videos show the controls and appear to be loading but at the end nothing can be played.  I also tried to do this from Dropbox and the similar happened.

For Youtube, I tried
st.video("https://www.youtube.com/embed/ywYcZCyqOBQ?modestbranding=1&rel=0", format='video/mp4', start_time=0)
(with or without modestbranding, format, start_time etc)

For Vimeo the same command but no error is produced. It simply does not work.

On the side, I also tried a 'component'
from streamlit_player import st_player
st_player("https://www.youtube.com/embed/ywYcZCyqOBQ")
This one produces an error saying that the component could not be run.

No luck.

Expected behavior is that these should work like other photos etc do.

Any solutions for this?

Thanks.

**Comment by whitphx** [comment]
Thank you for the report.
It's a bug with the desktop version. I will fix it.

**Comment by whitphx** [comment]
Dev note:

For this specific problem, we can simply add `frame-src https://*.youtube.com` to the CSP directive [here](https://github.com/whitphx/stlite/blob/f8d61a669bdbd78e7ce66ad6a695312b34d8dbbe/packages/desktop/craco.config.js#L23-L40).
However, it looks like such an allowed list-way does not work because there are much wider possibilities of resource references. For example, `streamlit_player` may also create an iframe referring to `soundcloud.com` like [the sample](https://github.com/okld/streamlit-player).

Therefore, it seems that **we should omit the CSP setting ignoring the [Electron best practice](https://www.electronjs.org/docs/latest/tutorial/security#7-define-a-content-security-policy) and accepting some risks like XSS** and keep the security level by applying [other best practices](https://www.electronjs.org/docs/latest/tutorial/security).

**Comment by whitphx** [comment]
This should be fixed with v0.17.0. Please try it.

**Comment by ulugeyik** [comment]
Thank  you. I will check it.
