### ISSUE TITLE
firefox support for cdn and vscode extension within the browser

### ISSUE THREAD

**Issue by franciscobmacedo** [whitphx/stlite#556]
If using the cdn link in html (link the example in the readme) and if opened in firefox it doesn't load:

```
Security Error: Content at path/to/index.html may not load data from https://cdn.jsdelivr.net/npm/@stlite/mountable@0.31.0/build/static/js/6073.384829d1.chunk.js.
```

The same behavior seems to happen in the dev environment of github (`github.dev`) when using the vscode extension - it doesn't work in firefox, although it works on other browsers.

**Comment by patrickm663** [comment]
I am having the same issue when replicating the example in the README using Firefox. Have you found a solution?

**Comment by quantumalchemy** [comment]
anyone find a solution to this?
firefox : Security Error: Content at http://localhost/stl.html may not load data from https://cdn.jsdelivr.net/npm/@stlite/mountable@0.39.0/build/static/js/6073.ade8ee62.chunk.js. 
only works in chrome and file served from online server or localhost
not local file - would be great if you could use this as a standalone file

**Comment by franciscobmacedo** [comment]
No solution for this yet...

**Comment by jessemorros** [comment]
Adding to this, I get the same behavior and the same error message.  I'm seeing "not same-origin" as the actual cause in the console.  "GET | https://cdn.jsdelivr.net/npm/@stlite/mountable@0.39.0/build/static/js/6073.ade8ee62.chunk.js". This error is typically because of mismatched http/https. To me the security certificate for the script url looks legit.

My app is hosted through Git Hub pages with a custom domain and "enforce HTTPS" enabled, but I had the same issue loading the page locally. 

The app works fine in Chrome on a MacBook and Firefox mobile on iOS. The issue only appears in Firefox desktop on OSX. I haven't tested other desktop versions of Firefox. 

```
GET /npm/@stlite/mountable@0.39.0/build/static/js/6073.ade8ee62.chunk.js undefined
Host: cdn.jsdelivr.net
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
```

**Comment by maxibor** [comment]
Same problem with a stlite app hosted on gh-pages, the app doesn't load and I get a 
`Security Error: Content at https://gh-pages-location/myapp.url may not load data from https://cdn.jsdelivr.net/npm/@stlite/mountable@0.52.1/build/static/js/8779.995e8fcf.chunk.js.`

Using Firefox 124.0.1 on macOS

**Comment by bethac07** [comment]
Another one for the pile for "hosted on GH pages (I have one app with a custom domain and one with the GH pages domain), doesn't work in firefox" stlite 

```
Security Error: Content at https://coba-nih.github.io/2023_ImageAnalysisSurvey/ may not load data from https://cdn.jsdelivr.net/npm/@stlite/mountable@0.60.2/build/static/js/1898.2c55d1d7.chunk.js.
```
