### ISSUE TITLE
AttributeError: module 'streamlit' has no attribute 'html'

### ISSUE THREAD

**Issue by OmarSa90** [whitphx/stlite#654]
Thank you for this wonderful project, does stlite supports st.html?

from pyecharts.charts import Bar
from pyecharts import options as opts
import streamlit as st

c = (Bar()
    .add_xaxis(["Microsoft", "Amazon", "IBM", "Oracle", "Google", "Alibaba"])
    .add_yaxis('2017-2018 Revenue in (billion $)', [21.2, 20.4, 10.3, 6.08, 4, 2.2])
    .set_global_opts(title_opts=opts.TitleOpts(title="Top cloud providers 2018", subtitle="2017-2018 Revenue"),
                     toolbox_opts=opts.ToolboxOpts())
    .render_embed() # generate a local HTML file
)
st.html(c, width=1000, height=1000)

Also i have include pyecharts as requirements, however i got this error message   AttributeError: module 'streamlit' has no attribute 'html'

#i took pye code from streamlit discussion
https://discuss.streamlit.io/t/streamlit-echarts/3655?page=2

**Comment by whitphx** [comment]
Looks like that code doesn't work even on the normal Streamlit because there is not the method `st.html()`.
Maybe the correct one is [`st.components.v1.html`](https://docs.streamlit.io/library/components/components-api).

It looks working on stlite as well:
https://edit.share.stlite.net/#!ChBzdHJlYW1saXRfYXBwLnB5EooEChBzdHJlYW1saXRfYXBwLnB5EvUDCvIDZnJvbSBweWVjaGFydHMuY2hhcnRzIGltcG9ydCBCYXIKZnJvbSBweWVjaGFydHMgaW1wb3J0IG9wdGlvbnMgYXMgb3B0cwppbXBvcnQgc3RyZWFtbGl0IGFzIHN0CgpjID0gKEJhcigpCi5hZGRfeGF4aXMoWyJNaWNyb3NvZnQiLCAiQW1hem9uIiwgIklCTSIsICJPcmFjbGUiLCAiR29vZ2xlIiwgIkFsaWJhYmEiXSkKLmFkZF95YXhpcygnMjAxNy0yMDE4IFJldmVudWUgaW4gKGJpbGxpb24gJCknLCBbMjEuMiwgMjAuNCwgMTAuMywgNi4wOCwgNCwgMi4yXSkKLnNldF9nbG9iYWxfb3B0cyh0aXRsZV9vcHRzPW9wdHMuVGl0bGVPcHRzKHRpdGxlPSJUb3AgY2xvdWQgcHJvdmlkZXJzIDIwMTgiLCBzdWJ0aXRsZT0iMjAxNy0yMDE4IFJldmVudWUiKSwKdG9vbGJveF9vcHRzPW9wdHMuVG9vbGJveE9wdHMoKSkKLnJlbmRlcl9lbWJlZCgpICMgZ2VuZXJhdGUgYSBsb2NhbCBIVE1MIGZpbGUKKQpzdC5jb21wb25lbnRzLnYxLmh0bWwoYywgd2lkdGg9MTAwMCwgaGVpZ2h0PTEwMDApGglweWVjaGFydHM,
