### ISSUE TITLE
Request Autofill.enable failed.

### ISSUE THREAD

**Issue by jafa2222** [whitphx/stlite#907]
When use Groq API in code and  using npm run serve, the following error is shown in the terminal:

```
[31612:0103/200452.271:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/prot
ocol_client/protocol_client.js (1)
```

Also, this error is shown in electron after the user's request:
![image](https://github.com/whitphx/stlite/assets/121040891/650a0fa2-9ac6-4dfd-8c0e-424870cec063)

**Comment by whitphx** [comment]
Seems like the "Request Autofill.enable failed" can be ignored as https://github.com/electron/electron/issues/41614 and it's independent from the request time-out error.

The request time-out may be due to some network access library usage, while I'm not sure what HTTP library is used in the Groq client.
Ref: https://github.com/whitphx/stlite?tab=readme-ov-file#http-requests
