### ISSUE TITLE
Mounting local filesystem does not work in MS Windows

### ISSUE THREAD

**Issue by erwan2397** [whitphx/stlite#973]
Running the ['nodefs persistence' example](https://github.com/whitphx/stlite/tree/main/packages/desktop/samples/file-persistence-nodefs) does not work under MS Windows.

To reproduce, go to the `packages/desktop/samples/file-persistence-nodefs` (or just copy the `app.py` and `package.json` files) then:

```
npm run dump
npm run serve
```

An error shows up:

![Screenshot 2024-06-11 160218](https://github.com/whitphx/stlite/assets/172401670/d1feaf64-ca90-4958-b820-bb7e49ea9b96)

Another message is shown in the main window: 

```
Error during boot up

Only URLs with a scheme in: file, data, node, and electron are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

I tried to modify the path in `package.json` in different ways, e.g.

```
       "nodefsMountpoints": {
          "/mnt": "file:///Users/....."
        }
```

Nothing worked, the same error always occurs.

**Comment by whitphx** [comment]
Thanks, this seems to be fixed in 0.58.1. Plz try the latest release.

**Comment by drose15-chwy** [comment]
Hi!

Stlite's (especially Desktop!) an incredibly useful tool - thank you for creating it. 

I know this issue is closed but I have what I think is a related question: is there any support or possible work around for handling not just relative path references but also those expressed with path shortcuts -- a la "~/Documents" on OSX or "%userprofile%\Documents" on Windows machines?

**Comment by whitphx** [comment]
@drose15-chwy Hi, that's a nice point. I created a separate issue for it: https://github.com/whitphx/stlite/issues/985
